services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: hbd_dev_web
    command: "python run.py"
    volumes:
      - .:/app
    ports:
      - 8000:5000
    env_file:
      - .env
    depends_on:
      - redis
      - worker
      - beat
  redis:
    image: redis
  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    image: celery
    command: "celery -A src.app:celery worker --loglevel=info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery
    command: "celery -A src.app:celery beat --loglevel=info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
