services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: hbd_dev_web
    command: "python run.py"
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - .env
    links:
        - redis
        - celery
    depends_on:
      - redis
  redis:
    image: redis
    ports:
        - 6379:6379
  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    image: celery
    command: "celery -A src.app:celery worker --loglevel=info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: celery
    command: "celery -A src.app:celery beat --loglevel=info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
